### ISSUE TITLE
Home Asssitant Example

### ISSUE THREAD

**Issue by anhnvme** [richahl/mqttmiot-dmaker1c#3]
Hello,

Can u show me example for home asssisant ?
Or the command turn on fan ?

Thanks

**Comment by richahl** [comment]
Yes sure, this is how I setup the fan in Home Assistant, I use 'mifan' as mqtt_prefix.

```
fan:
  - platform: mqtt
    name: "Xiaomi Smart Fan"
    state_topic: "mifanpower/state"
    command_topic: "mifanpower"
    oscillation_state_topic: "mifanrotate/state"
    oscillation_command_topic: "mifanrotate"
    speed_state_topic: "mifanfanspeed/state"
    speed_command_topic: "mifanfanspeed"
    qos: 0
    payload_on: "ON"
    payload_off: "OFF"
    payload_oscillation_on: "ON"
    payload_oscillation_off: "OFF"
    payload_low_speed: "LOW"
    payload_medium_speed: "MEDIUM"
    payload_high_speed: "HIGH"
    speeds:
      - low
      - medium
      - high
```
